"""empty message

Revision ID: e3a72b769dd5
Revises: 
Create Date: 2021-03-30 08:55:25.419871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3a72b769dd5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_details',
    sa.Column('payment_detail_id', sa.Integer(), nullable=False),
    sa.Column('card_owner_name', sa.String(length=100), nullable=False),
    sa.Column('cardnumber', sa.String(length=16), nullable=False),
    sa.Column('expiration_date', sa.String(length=5), nullable=False),
    sa.Column('security_code', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('payment_detail_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_details')
    # ### end Alembic commands ###
